/**:
  ros__parameters:
    port: "/dev/serial/by-id/usb-1a86_USB_Single_Serial_5B42134784-if00"
    id: "my_awesome_follower_arm"
    calibration_dir: "/home/user_lerobot/.cache/huggingface/lerobot/calibration/robots/so_follower"
    use_degrees: true
    enable_urdf_calibration: true
    urdf_calibration_file: "/workspace/so101_urdf_calibration.json"
    max_relative_target: 0
    disable_torque_on_disconnect: true
    publish_rate: 50.0
